### ISSUE TITLE
Closures

### ISSUE THREAD

**Issue by robbrit** [zhemao/glisp#15]
At the moment it is not possible to have closures, is it possible to add them?

Example:

```clojure
(defn adder [x] (fn [y] (+ x y)))
(def add5 (adder 5))
(add5 2)
; Would expect to see 7, but we get:
; error in __anon74:1: symbol x not found
```

It looks like the closure does not keep the surrounding scope.

**Comment by zhemao** [comment]
The way bytecode for function calls is generated now makes adding closures rather non-trivial. I'll consider adding support, but I must admit that I probably won't have time to do this.

**Comment by robbrit** [comment]
Yeah I was poking around through the code and realized that after a little while.

Don't go out of your way to do it. It's a deal-breaker for me since the way I write functional code often involves lots of closures, but Go has them so I'm find with sticking to that for now!
