### ISSUE TITLE
Clojure Full Implementation

### ISSUE THREAD

**Issue by Immortalin** [zhemao/glisp#16]
Hi, this lisp implementation closely resembles Clojure, how different is it from Clojure? Can you implement it as a complete Clojure compiler? I am thinking of using it for as a scripting language for a emacish text editor I am making and I do not want users have to completely learn a new scripting language. If it is exactly the same as Clojure, code can be reused. Thanks in advance!

**Comment by zhemao** [comment]
This is not a full implementation of Clojure. It is a separate LISP dialect with some superficial similarities in syntax.
