### ISSUE TITLE
请问这是完整实现Scheme规范的lisp实现项目吗？

### ISSUE THREAD

**Issue by insionng** [zhemao/glisp#17]
我打算内置在我的Go项目里，作为插件的解析语言，但是不知到目前为止这个实现是不是已经完整了？

**Comment by insionng** [comment]
譬如项目究竟是遵从R5RS还是R6RS标准之类，能否明确标识出来？

http://www.schemers.org/Documents/Standards/R5RS/
http://www.schemers.org/Documents/Standards/R6RS/

**Comment by zhemao** [comment]
No, glisp does not conform to any Scheme or Common Lisp standard. It is a small experimental Lisp dialect.

Also, I grew up in the US, so my Chinese is not very good. Please post any future communication in English.
