### ISSUE TITLE
Function parameter names seem to collide in the same scope.

### ISSUE THREAD

**Issue by chrhlnd** [zhemao/glisp#19]
```
(defn foldl [lst fun acc]
	(cond
		(empty? lst) acc
		(foldl (cdr lst) fun (apply fun (append (append [] (car lst)) acc)))))

(defn filter [lst fun1]
	(foldl lst
			(fn [x l]
				(cond
					(apply fun1 (append [] x)) (append l x)
					l))
			[])
)

(defn even? [x]
	(cond
		(number? x)
			(cond
				(float? x) false
				(= (bit-and x 1) 0))
			false
			))


(map (fn [x]
		(print "Even: ")
		(print x)
		(print "\n"))
	(filter [1 2 3 4 5 6 7 8 9 10] even?)
)
```
This will work and output

Even: 2
Even: 4
Even: 6
Even: 8
Even: 10

If the above filter definition also uses `fun` as a parameter though, it'll error out saying the applied function needs one more parameter, as if its matching the `fun` definition in foldl.

**Comment by zhemao** [comment]
Sorry, I didn't notice this issue until now. I'll take a look at it.

**Comment by zhemao** [comment]
I think I see what the problem is here. The scope hierarchy is set up in the following way

    filter
     -> foldl
           -> anonymous function

The scope search happens from the innermost function going up, so the first instance of "fun" it finds is in foldl, which is not the one we want.
