### ISSUE TITLE
how to add source function for reading expressions from another file

### ISSUE THREAD

**Issue by glycerine** [zhemao/glisp#21]
Hi Howard,

I'm trying to add a (source "path_to_script") functionality.

My modifications are here, https://github.com/glycerine/glisp, see especially the interpreter/source.go file (I tried to copy from the runScript() function in main.go). Unfortunately my env.Run() call is always returning the error 'invalid stack access asked for 0 Top was -1', about which I am mystified.

Could you suggest what I need to correct to get (source "script") to work?  I would like to be able to execute other scripts from within a script.

Thank you!

Jason

~~~

~~~

**Comment by glycerine** [comment]
@zhemao, I think I got it working--still would appreciate it if you could comment on the correctness of this approach, as I'm just guessing here: from my revised interpreter/source.go: adding an env2 := env.Duplicate() call and then using that in RunScript() seems to solve the problem.
~~~
func SourceFunction(env *Glisp, name string, args []Sexp) (Sexp, error) {
    fmt.Printf("\n SourceFunction started!\n")
    if len(args) != 1 {
        return SexpNull, WrongNargs
    }

    env2 := env.Duplicate()

    switch t := args[0].(type) {
    case SexpStr:
        RunScript(env2, string(t))
    default:
        return SexpNull, errors.New(
            fmt.Sprintf("argument to %s must be string: the path to source", name))
    }
  
    return SexpNull, nil
}
~~~

**Comment by chrhlnd** [comment]
Running it in a duplicate environment isn't going to have things resolvable back in the main environment. I made an update on my fork to support sourcing into the environment. I can submit it as a PR as well.

https://github.com/chrhlnd/glisp/commit/13f4c60a2c560f220a5c0fe52e8b3dcd3ab0c399

The stack error you're getting is because... there is no data stack when calling a user function, so you have to push and pop something when trying to evaluate the expressions that got parsed. In the commit above I added the method source-file which will... source files into the environment. In the test folder there is a source-include.glisp that includes some other files there.

**Comment by zhemao** [comment]
I think if we want to support something like imports, it should be done during code generation and not at runtime. Basically, it would be something similar to macro expansion. At runtime, if it finds that the statement is something like `(include "path-to-file")`, it will read in the specified file and run the generator on the included code.

**Comment by chrhlnd** [comment]
Ok I added a codgen version and made a pr, the run-time version could be useful if things are getting copied around and you want to dynamically populate while the script is executing. This could be in a support repo as well, but it relies on the Source* functions in the environment.go file.

**Comment by glycerine** [comment]
@chrhlnd, cool, I'll check out your new code. And thanks for that.

For my uses, I do need the runtime, as sourcing at the repl is what is required.

> Running it in a duplicate environment isn't going to have things resolvable back in the main environment.

Odd that it actually *does* work then. Note that env.Duplicate() does a shallow copy, since slices act like pointers. I just didn't (and still don't) understand why the env.Duplicate() made it work, nor what the original error was trying to say. I'd still appreciate any illumination on these points.

I'm refactoring the repl part that is in main to be in the interpreter library, so the repl can be used in the library. Let me know if you'd like a PR for that.  It's currently just on branch in https://github.com/glycerine/glisp/tree/fieldspec

**Comment by chrhlnd** [comment]
As far as the stack error. I made it panic at one point to see what was causing the pop

**Comment by glycerine** [comment]
@zhemao Hi Howard,

 Sorry, my comment earlier reflected confusion on my part about the distinction you were making -- could you explain the difference between "runtime" and "codegen" time?  Perhaps naively I thought of all codegen happening at runtime in an interpreter, does it not?

> I think if we want to support something like imports, it should be done during code generation and not at runtime. Basically, it would be something similar to macro expansion. At runtime, if it finds that the statement is something like (include "path-to-file"), it will read in the specified file and run the generator on the included code.
