### ISSUE TITLE
eval seems broken

### ISSUE THREAD

**Issue by glycerine** [zhemao/glisp#23]
with the env.ImportEval() in place in the REPL, how is eval supposed to work? I'm not getting anything out of it--
~~~
> (eval "def a 123")
error in eval:-1: Error calling eval: invalid stack access asked for 0 Top was -1
in __main:4
> a
error in __main:0: symbol {a 97} not found
> 

> (eval (quote (def a 12)))
error in eval:-1: Error calling eval: invalid stack access asked for 0 Top was -1
in __main:3
> 
~~~

**Comment by zhemao** [comment]
Yeah, sorry about that. It's fixed now in master.

**Comment by zhemao** [comment]
And you should use the latter syntax. Eval evaluates expressions, not code in strings. So the first one would just give you the string back. The second one will actually define a.

**Comment by glycerine** [comment]
Cool. Thanks Howard!
